// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwecvdcjGj0JupJ1_7PFWQedvFd4iC6k',
    appId: '1:292156705530:web:a6ec2b2fea8cfcdcda1743',
    messagingSenderId: '292156705530',
    projectId: 'wyszukiwarka-darmowych-gier',
    authDomain: 'wyszukiwarka-darmowych-gier.firebaseapp.com',
    storageBucket: 'wyszukiwarka-darmowych-gier.firebasestorage.app',
    measurementId: 'G-0RBC6498BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClzbOEc3EN9V2wkHka8P-YrC_S_Y6MjIA',
    appId: '1:292156705530:android:f4899347496c6761da1743',
    messagingSenderId: '292156705530',
    projectId: 'wyszukiwarka-darmowych-gier',
    storageBucket: 'wyszukiwarka-darmowych-gier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqo_V_HrY9PNU1h5kD1P0Z787vlrOHdL4',
    appId: '1:292156705530:ios:b56579a95762f4bfda1743',
    messagingSenderId: '292156705530',
    projectId: 'wyszukiwarka-darmowych-gier',
    storageBucket: 'wyszukiwarka-darmowych-gier.firebasestorage.app',
    iosBundleId: 'com.example.projektZaliczeniowy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqo_V_HrY9PNU1h5kD1P0Z787vlrOHdL4',
    appId: '1:292156705530:ios:b56579a95762f4bfda1743',
    messagingSenderId: '292156705530',
    projectId: 'wyszukiwarka-darmowych-gier',
    storageBucket: 'wyszukiwarka-darmowych-gier.firebasestorage.app',
    iosBundleId: 'com.example.projektZaliczeniowy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxwecvdcjGj0JupJ1_7PFWQedvFd4iC6k',
    appId: '1:292156705530:web:d9e3bc886a3aa098da1743',
    messagingSenderId: '292156705530',
    projectId: 'wyszukiwarka-darmowych-gier',
    authDomain: 'wyszukiwarka-darmowych-gier.firebaseapp.com',
    storageBucket: 'wyszukiwarka-darmowych-gier.firebasestorage.app',
    measurementId: 'G-2S8EDFHTE8',
  );
}
